site_name: Dr. Emilio Zamorano de Acha
site_url: https://emiliozamorano15.github.io

nav:
  - Home: index.md
  # - About: about.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: indigo
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: indigo
      accent: purple

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/emiliozamorano15
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/emiliozamoranodeacha/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list

copyright: |
  &copy; 2023 <a href="https://emiliozamorano15.github.io"  target="_blank" rel="noopener">Emilio Zamorano</a>